[package]
distribution = "2201.12.2"
org = "ballerinax"
name = "aws.s3"
version = "5.0.0"
license = ["Apache-2.0"]
authors = ["Ballerina"]
keywords = ["Content & Files/File Management & Storage", "Cost/Paid", "Vendor/Amazon"]
icon = "icon.png"
repository = "https://github.com/ballerina-platform/module-ballerinax-aws.s3"

[[platform.java21.dependency]]
groupId = "io.ballerina.stdlib"
artifactId = "http-native"
version = "5.0.0"
path = "../native/build/libs/native-5.0.0-SNAPSHOT.jar"
