[package]
org = "ballerinax"
name = "aws.s3"
version = "5.0.0"
distribution = "2201.12.10"
authors = ["Ballerina"]
keywords = ["Content & Files/File Management & Storage", "Cost/Paid", "Vendor/Amazon"]
repository = "https://github.com/ballerina-platform/module-ballerinax-aws.s3"
license = ["Apache-2.0"]
icon = "icon.png"

[build-options]
observabilityIncluded = true

[[platform.java21.dependency]]
path = "./lib/aws-s3-native-5.0.0.jar"
groupId = "org.ballerinax.aws.s3"
artifactId = "aws-s3-native"
version = "5.0.0"
